- name: Downloading
  unarchive:
    src: "{{ archive.source }}"
    dest: "{{ archive.path }}"
    remote_src: yes
    creates: "{{ archive.path }}/aws/install"

- name: Installing
  command:
    cmd: "{{ archive.path }}/aws/install"
    creates: /usr/local/bin/aws
