---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  roles:
    # Common roles
    # - { role: common, become: true }
    # - { role: zsh, become: true }
    # - { role: dotfiles, become: true }
    # - { role: projects-installer }
    - { role: docker, become: true }
    - { role: aws-cli }
    # - { role: keybase }

    # - { role: desktop-preferences-unity }
    # - { role: adapta-theme, become: true }
