- name: Adding repository
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb

- name: Installing
  package:
    name: keybase
    state: present

- name: Running
  command: run_keybase
  args:
    creates: ~/.config/autostart/keybase_autostart.desktop
