- name: Add fasd repository
  apt_repository:
    repo: ppa:aacebedo/fasd
    state: present

- name: Add hub repository
  apt_repository:
    repo: ppa:cpick/hub
    state: present

- name: Add ssh-vault
  apt:
    deb: "https://dl.bintray.com/nbari/ssh-vault/ssh-vault_{{ ssh_vault.version }}_{{ ssh_vault.packaging }}"

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Adding useful stuff
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - axel
    - direnv
    - chromium-browser
    - fasd
    - fzy
    - htop
    - hub
    - jq
    - lnav
    - localepurge
    - silversearcher-ag
    - tig
    - tlp
    - tlp-rdw
    - tmux
    - tree
    - vim
    - yank

- name: Removing useless stuff
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - aisleriot
    - apache2
    - gnome-mahjongg
    - gnome-mines
    - gnome-software-plugin-snap
    - gnome-sudoko
    - rhythmbox
    - shotwell
    - snapd
    - thunderbird

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Remove snap system cache
  file:
    state: absent
    path: /var/cache/snapd/

- name: Remove user snap
  file:
    state: absent
    path: $HOME/snap

- name: Fancy apt progress
  copy:
    dest: /etc/apt/apt.conf.d/99progressbar
    content: |
      Dpkg::Progress-Fancy "%1b[40m";
      APT::Color "1";

- name: Override AD to set default shell
  copy:
    dest: /etc/sssd/conf.d/00-shell.conf
    mode: '0600'
    content: |
      [nss]
      override_shell = /usr/bin/zsh

- name: Automatically (dis)connect from and to Wifi on docked status change
  replace:
    path: /etc/default/tlp
    regexp: '^#\s*(DEVICES_TO_.+ABLE_ON_LAN_.*CONNECT)'
    replace: '\1'

- name: Runnable Elastic Docker containers
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present

# https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Jetbrains IDE settings
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present
