- name: Installing apt-key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding deb repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Installing Docker
  apt:
    pkg: docker-ce
    state: latest

- name: Creating Docker group
  group:
    name: docker
    state: present

- name: Adding current user to Docker group
  user:
    name: {{ ansible_env.USER }}
    groups: docker
    append: yes

- name: "Ensuring Docker is {{ docker.start | ternary('started','stopped') }}"
  service:
    name: docker
    state: {{ docker.start | ternary('restarted','stopped') }}
    enabled: {{ docker.service_enabled }}

- name: Installing Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker-compose.version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    force: no
    mode: 0755
